### ISSUE TITLE
Stargate returns XML instead of JSON?!

### ISSUE THREAD

**Issue by al6x** [greglu/hbase-stargate#1]
Hi I have problems with Stargate, it always returning XML responses, no matter what you specified in the 'Accept' property of header?

Tried HBase 0.20.4, 0.20.6, 0.89.20100726 - all of them are returning XML and consequently hbase-stargate doesn't work (because it expect json).

Do you have such problems?

**Comment by greglu** [comment]
I cannot replicate this problem. Can you try again with the latest version of HBase (0.90.4)? I've updated the library to work with the newer version and I also replaced the HTTP client with Patron (instead of using net/http). Hopefully all the changes fixed your problem.

Please reopen this case if you're still having issues.

**Comment by elizeu** [comment]
This is an old discussion, but the answer below might benefit others.

Short answer: Check whether the URL you are sending with your GET/POST request have _only one_ sequence of '\r\n' characters in the end. 

Longer answer: I found the behavior you descibe when sending an HTTP GET request using a URL that comes back from a POST request sent previously. For example, a POST is sent for Scanner creation, a URL is returned in the Location: <url> field of the HTTP response.

As the response has '\r\n' at the end of each line of the HTTP message header. I was inadvertently using the value directly to send a GET request and appending another '\r\n' to the end of the GET line in the new header. So, the rest of the messages was skipped by the HBase REST server.

I hope it helps.
